services:
  - name: tactology-nest-test
    type: web
    env: alpine
    build:
      dockerfile: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    port: 3000